ALTER TABLE APPS.XXD_DAX_ANSWER
 DROP PRIMARY KEY CASCADE;

DROP TABLE APPS.XXD_DAX_ANSWER CASCADE CONSTRAINTS PURGE;

CREATE TABLE APPS.XXD_DAX_ANSWER
(
  ID                  NUMBER,
  EBS_TRANSACTION_NO  VARCHAR2(20 BYTE)         NOT NULL,
  TRANS_TYPE		 VARCHAR2(8) 			NOT NULL,
  SENT_DATE           DATE                      DEFAULT SYSDATE               NOT NULL,
  CONFIRMED           VARCHAR2(1 BYTE)          DEFAULT 'Y'                   NOT NULL,
  FLD                 VARCHAR2(200 BYTE),
  VAL                 VARCHAR2(200 BYTE),
  INFO                VARCHAR2(4000 BYTE),
  WARNING             VARCHAR2(4000 BYTE),
  ERR                 VARCHAR2(4000 BYTE),
  FAULT               VARCHAR2(4000 BYTE)
)
TABLESPACE APPS_TS_TX_DATA;


--  There is no statement for index APPS.SYS_C00289871.
--  The object is created when the parent object is created.

CREATE INDEX APPS.XXD_DAX_ANSWER_I1 ON APPS.XXD_DAX_ANSWER
(EBS_TRANSACTION_NO, SENT_DATE, CONFIRMED)
TABLESPACE APPS_TS_TX_DATA;

DROP SEQUENCE APPS.XXD_DAX_ANSWER_SEQ;

CREATE SEQUENCE APPS.XXD_DAX_ANSWER_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE OR REPLACE TRIGGER APPS.XXD_DAX_ANSWER_TRG
BEFORE INSERT
ON APPS.XXD_DAX_ANSWER
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  :new.ID := XXD_DAX_ANSWER_SEQ.nextval;
END XXD_DAX_ANSWER_TRG;
/


ALTER TABLE APPS.XXD_DAX_ANSWER ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE APPS_TS_TX_DATA
  ENABLE VALIDATE);

